project:
  type: website

website:
  title: "QUACK"
  navbar:
    left:
      - href: Page_QuickStart/quickstart.qmd
        text: Quack Start
      - text: Detailed Instructions
        menu:
        - text: Ordering
          href: Page_Ordering/ordering_overview.qmd
        - text: Assembly
          href: Page_Assembly/assembly_overview.qmd
        - text: Installation
          href: Page_Installation/installation.qmd
      - text: Documentation
        menu:
        - text: Hardware
          href: Page_Documentation/hardware_doc/hardware_doc.qmd
        - text: Software
          href: Page_Documentation/software_doc/software_doc.qmd
      - text: Other Resources
        href: Page_Resources/resources.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



